openapi: 3.0.3

info:
  title: Populon Sport Diary REST API
  version: v1

servers:
  - url: http://localhost:8080/v1
    description: Local server

components:
  responses:
    "400":
      description: When request is invalid
      content:
        application/problem+json:
          schema:
            type: object
    "401":
      description: When user is not authenticated
      content:
        application/problem+json:
          schema:
            type: object
    "403":
      description: When user is not authorized to perform this operation
      content:
        application/problem+json:
          schema:
            type: object
    "404":
      description: When resource with given identifier is not found
      content:
        application/problem+json:
          schema:
            type: object
  schemas:
    BaseItemVO:
      type: object
      properties:
        id:
          description: Unique identifier
          type: integer
          format: int64
          readOnly: true
        name:
          description: Item name
        version:
          description: Item version
      required:
        - id
        - name
        - version


paths:
  /frameworks:
    get:
      operationId: Retrieve Items
      description: Retrieve all items
      tags:
        - Frameworks
      responses:
        "200":
          description: When operation is successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BaseItemVO"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
